version: 'latest'

services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./data/postgres/:/var/lib/postgres
    ports:
      - '5432:5432'
    env_file:
      .env
